### ISSUE TITLE
[friend]:华仔927のBlog

### ISSUE THREAD

**Issue by ghost** [GC-ZF/Comment-Backups#1]
### 网站运行了多长时间？ || How long has the site been up and running?

新建没多久 || just soon

### 什么类型的博客 || What kind of blog?

都有

### 填写友链 || input your blog information?

 每个字段前请保留空格 
 name: 华仔927のBlog
 link: https://blog.xiaohua927.top/
 avatar: https://i.imgtg.com/2022/10/27/P6rV6.jpg
 descr: 行而不辍，未来可期！

**Comment by GC-ZF** [comment]
抱歉最近在忙，已添加，坚持更新哦
