### ISSUE TITLE
MONGODB_URI和DB_NAME问题

### ISSUE THREAD

**Issue by cao-gift** [GC-ZF/Comment-Backups#3]
你好，我的是这种形式，？前面什么都没有，请问MONGODB_URI和DB_NAME分别是什么
mongodb+srv://XXX:XXX@cluster0.6wluorl.mongodb.net/?retryWrites=true&w=majority

**Comment by GC-ZF** [comment]
到你新建的数据库下，点`Browse Collections`，下面有这些数据库的名称，你应该只有一个数据库，多余那俩我自己用的。如果你也有好多张的话，找包含comment表的那个，例如我的是myfirstdatabase

![image](https://user-images.githubusercontent.com/94956933/210709683-2a848aad-2b87-4e6e-83b6-dd031cfb646e.png)


![image](https://user-images.githubusercontent.com/94956933/210709726-b8e9ac02-e4dd-4805-b7ce-91cc34146e8e.png)
